# Generated by Django 4.0.2 on 2022-02-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_location_user_locations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.FloatField(),
        ),
    ]
