# Generated by Django 4.0.2 on 2022-03-16 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_selection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selection',
            old_name='owner',
            new_name='user',
        ),
    ]
